// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

import { test, runTests } from "./test"
import Gaze from "./gaze"
import Array from "array"
import Nibblers from "./nibblers"

runTests("Gaze Suite", [
    test("empty String input", () => {
        let gaze = Gaze.fromString("")
        assert(Gaze.isComplete(gaze))
        assert(Gaze.peek(gaze) == None)
        assert(Gaze.peek(gaze) == None)
        assert(Gaze.isComplete(gaze))
    }),
    test("empty array input", () => {
        let gaze = Gaze.fromArray(Array.make(0, "a"))
        assert(Gaze.isComplete(gaze))
        assert(Gaze.peek(gaze) == None)
        assert(Gaze.peek(gaze) == None)
        assert(Gaze.isComplete(gaze))
    }),
    test("init Gaze with one value", () => {
        let gaze = Gaze.fromArray(Array.make(1, "a"))
        assert(!Gaze.isComplete(gaze))
        assert(Gaze.peek(gaze) == Some("a"))
        assert(Gaze.peek(gaze) == Some("a"))
        assert(Gaze.next(gaze) == Some("a"))
        assert(Gaze.next(gaze) == None)
        assert(Gaze.isComplete(gaze))
    }),
    test("init Gaze with single char String", () => {
        let gaze = Gaze.fromString("a")
        assert(!Gaze.isComplete(gaze))
        assert(Gaze.peek(gaze) == Some('a'))
        assert(Gaze.peek(gaze) == Some('a'))
        assert(Gaze.next(gaze) == Some('a'))
        assert(Gaze.next(gaze) == None)
        assert(Gaze.isComplete(gaze))
    })
])

runTests("Take Suite", [
    test("take with single value", () => {
        let gaze = Gaze.fromString("a")
        assert(Gaze.attempt(Nibblers.take('a'), gaze) == Some(['a']))
        assert(Gaze.isComplete(gaze))
    })
])
