// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

import List from "list"
import { concat } from "string"

record Test { title: String, body: () -> Void }

export let test = (title, body) => {
    { title, body }
}

export let runTests = (tests: List<Test>) => {
    List.forEach((test) => {
        test.body()
        print(concat("SUCCESS - ", test.title))
    }, tests)
}
