// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

import { tokenize } from "./wander-lexer"
import { parse } from "./wander-parser"
import { interpret } from "./wander-interpreter"

export let run = script => {
    let tokens = tokenize(script)
    let tree = parse(tokens)
    interpret(tree)
}
