// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

import { isOk, isErr, toOption } from "result"
import { runTests, test, assertEq } from "../util/test"
import List from "list"
import { readIdentifier, readValue } from "./lig-read"
import { identifier, Integer, String } from "../ligature/ligature"

runTests("Read Lig", [
    test("read single Statement", () => {
        assertEq(readIdentifier("<a> <b> <c>"),
            toOption(identifier("hello")))
    }),
    // test("read Values", () => {
    //     assertEq(readValue("<hello>"), toOption(identifier("hello")))
    //     assertEq(readValue("1234"), Some(Integer(1234L)))
    //     assertEq(readValue("\"Hello\""), Some(String("Hello")))
    //     //TODO add bytes test case
    // })
])
