// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

import { test, runTests, assertEq } from "../util/test"
import Gaze from "./gaze"
import Array from "array"
import List from "list"
import Nibblers from "./nibblers"
import Number from "number"
import String from "string"
import { unwrap } from "result"

runTests("Gaze Suite", [
    test("empty String input", () => {
        let gaze = Gaze.fromString("")
        assert(Gaze.isComplete(gaze))
        assert(Gaze.peek(gaze) == None)
        assert(Gaze.peek(gaze) == None)
        assert(Gaze.isComplete(gaze))
    }),
    test("empty array input", () => {
        let gaze = Gaze.fromArray(Array.make(0, "a"))
        assert(Gaze.isComplete(gaze))
        assert(Gaze.peek(gaze) == None)
        assert(Gaze.peek(gaze) == None)
        assert(Gaze.isComplete(gaze))
    }),
    test("init Gaze with one value", () => {
        let gaze = Gaze.fromArray(Array.make(1, "a"))
        assert(!Gaze.isComplete(gaze))
        assert(Gaze.peek(gaze) == Some("a"))
        assert(Gaze.peek(gaze) == Some("a"))
        assert(Gaze.next(gaze) == Some("a"))
        assert(Gaze.next(gaze) == None)
        assert(Gaze.isComplete(gaze))
    }),
    test("init Gaze with single char String", () => {
        let gaze = Gaze.fromString("a")
        assert(!Gaze.isComplete(gaze))
        assert(Gaze.peek(gaze) == Some('a'))
        assert(Gaze.peek(gaze) == Some('a'))
        assert(Gaze.next(gaze) == Some('a'))
        assert(Gaze.next(gaze) == None)
        assert(Gaze.isComplete(gaze))
    })
])

runTests("Map Suite", [
    test("map numbers", () => {
        let gaze = Gaze.fromString("123")
        let result = Some([1, 2, 3])
        let nibbler = Gaze.map(
            Gaze.next,
            char => 
                unwrap(
                    Number.parse(toString(char))))
        assertEq(Gaze.attempt(Nibblers.repeat(nibbler), gaze), result)
    })
])

runTests("Take Suite", [
    test("take with single value", () => {
        let gaze = Gaze.fromString("a")
        assert(Gaze.attempt(Nibblers.take('a'), gaze) == Some('a'))
        assert(Gaze.isComplete(gaze))
    })
])

runTests("Take Cond Suite", [
    test("takeCond with a single value", () => {
        let gaze = Gaze.fromString("a")
        assertEq(Gaze.attempt(Nibblers.takeCond((c) => c == 'a'), gaze), Some('a'))
        assert(Gaze.isComplete(gaze))
    }),
    test("takeCond with multiple values", () => {
        let gaze = Gaze.fromString("cab")
        assertEq(Gaze.attempt(Nibblers.takeCond((c) => List.contains(c, ['a', 'b', 'c', 'd'])), gaze), Some('c'))
        assert(!Gaze.isComplete(gaze))
    }),
    test("takeCond match beginning", () => {
        let gaze = Gaze.fromString("abc123")
        assertEq(Gaze.attempt(Nibblers.takeCond((c) => List.contains(c, ['a', 'b', 'c', 'd'])), gaze), Some('a'))
        assert(!Gaze.isComplete(gaze))
    }),
    test("takeCond no match beginning", () => {
        let gaze = Gaze.fromString("123abc")
        assertEq(Gaze.attempt(Nibblers.takeCond((c) => List.contains(c, ['a', 'b', 'c', 'd'])), gaze), None)
        assert(!Gaze.isComplete(gaze))
    })
])

runTests("Take While Suite", [
    test("takeWhile with a single value", () => {
        let gaze = Gaze.fromString("a")
        assertEq(Gaze.attempt(Nibblers.takeWhile((c) => c == 'a'), gaze), Some(['a']))
        assert(Gaze.isComplete(gaze))
    }),
    test("takeWhile with multiple values", () => {
        let gaze = Gaze.fromString("cab")
        assertEq(Gaze.attempt(Nibblers.takeWhile((c) => List.contains(c, ['a', 'b', 'c', 'd'])), gaze), Some(['c', 'a', 'b']))
        assert(Gaze.isComplete(gaze))
    }),
    test("takeWhile match beginning", () => {
        let gaze = Gaze.fromString("abc123")
        assertEq(Gaze.attempt(Nibblers.takeWhile((c) => List.contains(c, ['a', 'b', 'c', 'd'])), gaze), Some(['a', 'b', 'c']))
        assert(!Gaze.isComplete(gaze))
    }),
    test("takeWhile no match beginning", () => {
        let gaze = Gaze.fromString("123abc")
        assertEq(Gaze.attempt(Nibblers.takeWhile((c) => List.contains(c, ['a', 'b', 'c', 'd'])), gaze), None)
        assert(!Gaze.isComplete(gaze))
    })
])

runTests("Take While Index Suite", [
    test("takeWhileIndex simple", () => {
        let gaze = Gaze.fromString("abc")
        assertEq(Gaze.attempt(Nibblers.takeWhileIndex((c, i) => { (c == 'a' && i == 0) || (c == 'b' && i == 1) }), gaze), Some(['a', 'b']))
        assert(!Gaze.isComplete(gaze))
    }),
])

runTests("Between Suite", [
    test("between simple", () => {
        let gaze = Gaze.fromString("abbbbbc")
        assertEq(Gaze.attempt(Nibblers.between('a', Nibblers.takeWhile((c) => c == 'b'), 'c'), gaze), Some(['b', 'b', 'b', 'b', 'b']))
        assert(Gaze.isComplete(gaze))
    })
])

runTests("Repeat Suite", [
    test("repeat simple", () => {
        let gaze = Gaze.fromString("aaaabbbbbc")
        assertEq(Gaze.attempt(Nibblers.repeat(Nibblers.takeCond((c) => c == 'a')), gaze), Some(['a', 'a', 'a', 'a']))
        assert(!Gaze.isComplete(gaze))
        assertEq(Gaze.attempt(Nibblers.repeat(Nibblers.takeCond((c) => c == 'b')), gaze), Some(['b', 'b', 'b', 'b', 'b']))
        assert(!Gaze.isComplete(gaze))
        assertEq(Gaze.attempt(Nibblers.repeat(Nibblers.takeCond((c) => c == 'c')), gaze), Some(['c']))
        assert(Gaze.isComplete(gaze))
    })
])

runTests("Take All Suite", [
    test("take all simple", () => {
        let gaze = Gaze.fromString("aaaabbbbbc")
        let takeAs = Nibblers.repeat(Nibblers.takeCond((c) => c == 'a'))
        let takeBs = Nibblers.repeat(Nibblers.takeCond((c) => c == 'b'))
        let takeCs = Nibblers.repeat(Nibblers.takeCond((c) => c == 'c'))
        let takeAll = Nibblers.takeAll([takeAs, takeBs, takeCs])
        assertEq(Gaze.attempt(takeAll, gaze), Some([['a', 'a', 'a', 'a'], ['b', 'b', 'b', 'b', 'b'], ['c']]))
    })
])

runTests("Take First Suite", [
    test("take first simple", () => {
        let gaze = Gaze.fromString("aaaabbbbbc")
        let takeAs = Nibblers.repeat(Nibblers.takeCond((c) => c == 'a'))
        let takeBs = Nibblers.repeat(Nibblers.takeCond((c) => c == 'b'))
        let takeCs = Nibblers.repeat(Nibblers.takeCond((c) => c == 'c'))
        let takeFirst = Nibblers.takeFirst([takeCs, takeBs, takeAs])
        assertEq(Gaze.attempt(takeFirst, gaze), Some(['a', 'a', 'a', 'a']))
    })
])
